### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by federicobond** [sbdchd/celery-types#109]
Hi @sbdchd, any chance we could get a release out within the next few weeks?

It would be great to have the latest fixes in a released version. Let me know if there is anything I can do to help.

**Comment by sbdchd** [comment]
oh yeah I haven't gotten around to automating that so it's pretty manual

need to setup https://github.com/marketplace/actions/pypi-publish at some point

**Comment by sbdchd** [comment]
should be all set! I've release 0.15.0

**Comment by federicobond** [comment]
Thank you! That's awesome ❤️

**Comment by pcorpet** [comment]
Bumping this issue to get the changes from July 2023 in a release please?

**Comment by sbdchd** [comment]
Done! Released 0.19.0

**Comment by aabed-aa** [comment]
Bumping this for new release request
