### ISSUE TITLE
[Question] self annotation

### ISSUE THREAD

**Issue by jochman** [sbdchd/celery-types#128]
How should I annotate celery when `bind=True` with `self`?

**Comment by sbdchd** [comment]
It's not pretty, but this is what we have in the tests:

https://github.com/sbdchd/celery-types/blob/7b909f027512a70914d22a6f9c6ec1e3e5d1a0b1/tests/test_celery.py#L22C1-L24

```python
@app.task(bind=True)
def add_2(self: Task[Any, Any], x: int, y: int) -> None:
    logger.info(self.request.id)
```

**Comment by jochman** [comment]
OK, thanks!

I think it'll be great to add it to the documentation
