### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by aabed-aa** [sbdchd/celery-types#149]
Is there a release schedule/process for this project? When will merged branches be released to pypi?

**Comment by sbdchd** [comment]
Yeah don't have anything automated setup unfortunately, have to do it all manually

**Comment by aabed-aa** [comment]
Is it possible to publish a new release?

**Comment by sbdchd** [comment]
Should be all set!

**Comment by aabed-aa** [comment]
Thanks!
