### ISSUE TITLE
Change `apply_async`'s `eta` to be `Optional[datetime]`

### ISSUE THREAD

**Issue by joeriddles** [sbdchd/celery-types#32]
Please change `apply_async`'s `eta` to be `Optional[datetime]`

https://github.com/sbdchd/celery-types/blob/737a5baaa44c28ba001dc3f6ffdf71e06d070f51/typings/celery/canvas.pyi#L43

**Comment by sbdchd** [comment]
There are probably more params that should also be nullable, but `eta` has been fixed in the latest version

thanks for the report!

**Comment by joeriddles** [comment]
Thank you @sbdchd 🙂
