### ISSUE TITLE
celery.app.Task.throws is a tuple of exception types?

### ISSUE THREAD

**Issue by jeking3** [sbdchd/celery-types#43]
The type seems to be incorrect?

https://github.com/sbdchd/celery-types/blob/4ac79235fe3df538e23d915a3e8a8febf6e6d316/celery-stubs/app/task.pyi#L35

In the other locations it is expressed as a tuple of exception types:

https://github.com/sbdchd/celery-types/search?q=throws

**Comment by sbdchd** [comment]
should be fixed in 0.9.1

Thanks for the report!
