### ISSUE TITLE
"Request" has no attribute "retries"

### ISSUE THREAD

**Issue by galonsky** [sbdchd/celery-types#87]
I believe the Request object does have a retries attribute: https://github.com/celery/celery/blob/b0cfa0d818743262a032c541cce2fa8c43fabad4/celery/app/task.py#L558

But the stubs seem to be missing that. Can that be added? If there's agreement, I can try to open a PR.

**Comment by sbdchd** [comment]
Yeah these stubs are missing a lot of little things, I probably should have used stub gen, but I basically started these stubs by only typing the parts of the API the codebase I was typing was using
