### ISSUE TITLE
Calling a chord object should return an AsyncResult

### ISSUE THREAD

**Issue by galonsky** [sbdchd/celery-types#91]
When you "call" a chord object, it [delegates](https://github.com/celery/celery/blob/master/celery/canvas.py#L1615) to `apply_async`, so the return value of something like
```python
chord([task1.s(), task2.s()])(callback.s())
```
should be `AsyncResult`

I tried adding this:
```python
    def __call__(
        self,
        body: Optional[Signature[Any]] = ...,
        **options: Any,
    ) -> celery.result.AsyncResult[Any]: ...
```

but mypy complains because this disagrees with Signature's typing:
```
typings/celery/canvas.pyi:376:5: error: Signature of "__call__" incompatible with supertype "Signature"  [override]
typings/celery/canvas.pyi:376:5: note:      Superclass:
typings/celery/canvas.pyi:376:5: note:          def __call__(self, *partial_args: Any, **partial_kwargs: Any) -> Any
typings/celery/canvas.pyi:376:5: note:      Subclass:
typings/celery/canvas.pyi:376:5: note:          def __call__(self, body: Optional[Signature[Any]] = ..., **options: Any) -> AsyncResult[Any]
```

is it possible to type this correctly?

**Comment by sbdchd** [comment]
oh yeah override errors!

99% of the time they're safe to ignore, and looking at the celery code and how most people use the types, we can `# type: ignore [override]` the function signature

the only time we can't ignore it, is if we're using the type in OOPy fashion, i.e., we subclass `dict` and try and pass it to a function that expects a `dict` -- aka https://en.wikipedia.org/wiki/Liskov_substitution_principle

So I think your solution looks great!
