### ISSUE TITLE
Task.max_retries has wrong type

### ISSUE THREAD

**Issue by jan-szejko-steelseries** [sbdchd/celery-types#98]
https://github.com/sbdchd/celery-types/blob/main/celery-stubs/app/task.pyi#L36
https://docs.celeryq.dev/en/v5.2.7/userguide/tasks.html#Task.max_retries

According to celery docs, it can have value `None`, but here it's declared as `int`. It should be `Optional[int]`,

**Comment by intgr** [comment]
This should be closed now.
